import { v4 as uuid } from 'uuid';
import { getAgent, updateAgent, getAgentVersions, revertAgent } from '../agents';
import { getDb } from '../../db';
import { logger } from '../../utils/logger';

export interface PromptDiff {
  original: string;
  proposed: string;
  changeNote: string;
}

export function detectCritique(message: string): boolean {
  const critiquePatterns = [
    /why did you/i,
    /that'?s wrong/i,
    /fix your/i,
    /don'?t do that/i,
    /you should/i,
    /instead of/i,
    /that was incorrect/i,
    /please change/i,
    /improve your/i,
    /stop doing/i,
    /next time/i,
    /you need to/i,
  ];

  return critiquePatterns.some(p => p.test(message));
}

export function generatePromptDiff(
  currentPrompt: string,
  critique: string,
  runOutput: string
): PromptDiff {
  // In production this would call Claude to analyze and propose changes.
  // Here we build the structured request for the agent to process.
  const changeNote = `Self-improvement based on critique: "${critique.slice(0, 100)}"`;

  return {
    original: currentPrompt,
    proposed: currentPrompt, // Placeholder — actual diff generated by Claude
    changeNote,
  };
}

export function applyPromptDiff(
  agentId: string,
  newPrompt: string,
  changeNote: string,
  changedBy: string
): { agent: ReturnType<typeof getAgent>; version: number } {
  const agent = updateAgent(agentId, { system_prompt: newPrompt }, changedBy);

  const versions = getAgentVersions(agentId);
  const latestVersion = versions[0]?.version || 1;

  logger.info('Self-improvement applied', {
    agentId,
    version: latestVersion,
    changeNote,
  });

  return { agent, version: latestVersion };
}

export function revertToVersion(
  agentId: string,
  version: number,
  changedBy: string
): ReturnType<typeof getAgent> {
  const agent = revertAgent(agentId, version, changedBy);

  logger.info('Agent reverted', { agentId, version, changedBy });
  return agent;
}

export function checkPromptSize(agentId: string): { tokenCount: number; warning: boolean } {
  const agent = getAgent(agentId);
  if (!agent) throw new Error(`Agent ${agentId} not found`);

  const tokenCount = Math.ceil(agent.system_prompt.length / 4);
  const WARNING_THRESHOLD = 4000;

  return {
    tokenCount,
    warning: tokenCount > WARNING_THRESHOLD,
  };
}

export function formatDiffForSlack(original: string, proposed: string): string {
  const originalLines = original.split('\n');
  const proposedLines = proposed.split('\n');

  const blocks: string[] = [];

  // Simple line-by-line diff
  const maxLines = Math.max(originalLines.length, proposedLines.length);
  for (let i = 0; i < maxLines; i++) {
    const origLine = originalLines[i] || '';
    const propLine = proposedLines[i] || '';

    if (origLine !== propLine) {
      if (origLine) blocks.push(`- ${origLine}`);
      if (propLine) blocks.push(`+ ${propLine}`);
    }
  }

  if (blocks.length === 0) return '_No changes detected_';

  return '```diff\n' + blocks.join('\n') + '\n```';
}
